### ISSUE TITLE
error installing Morpheus Macbook Pro (M2)

### ISSUE THREAD

**Issue by yijianglanl** [morpheus-lab/homebrew-morpheus#19]
(base) AS-MATH-MBP-07:~ yjiang12$ brew install morpheus
==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################## 100.0%
Warning: Treating morpheus as a formula. For the cask, use homebrew/cask/morpheus
==> Fetching morpheus-lab/morpheus/morpheus
==> Downloading https://gitlab.com/morpheus.lab/morpheus/-/archive/v2.3.5/morpheus-v2.3.5
Already downloaded: /Users/yjiang12/Library/Caches/Homebrew/downloads/d5688170e62f19984b9cc2b0c86c26bf61b18bdbe271e6c5a0bfc22ca5a6daf7--morpheus-v2.3.5.tar.gz
==> Installing morpheus from morpheus-lab/morpheus
==> cmake . -DMORPHEUS_RELEASE_BUNDLE=ON
==> make install
Last 15 lines from /Users/yjiang12/Library/Logs/Homebrew/morpheus/02.make:
20 errors generated.
make[5]: *** [src/CMakeFiles/sbml-static.dir/sbml/packages/comp/sbml/ListOfExternalModelDefinitions.cpp.o] Error 1
20 errors generated.
make[5]: *** [src/CMakeFiles/sbml-static.dir/sbml/packages/comp/extension/CompSBasePlugin.cpp.o] Error 1
make[5]: *** [src/CMakeFiles/sbml-static.dir/sbml/packages/comp/sbml/Deletion.cpp.o] Error 1
make[5]: *** [src/CMakeFiles/sbml-static.dir/sbml/packages/comp/sbml/ExternalModelDefinition.cpp.o] Error 1
make[5]: *** [src/CMakeFiles/sbml-static.dir/sbml/packages/comp/sbml/CompBase.cpp.o] Error 1
make[5]: *** [src/CMakeFiles/sbml-static.dir/sbml/packages/comp/extension/CompModelPlugin.cpp.o] Error 1
make[5]: *** [src/CMakeFiles/sbml-static.dir/sbml/packages/comp/extension/CompExtension.cpp.o] Error 1
make[5]: *** [src/CMakeFiles/sbml-static.dir/sbml/packages/comp/extension/CompSBMLDocumentPlugin.cpp.o] Error 1
make[4]: *** [src/CMakeFiles/sbml-static.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [3rdparty/libSBML/libSBML-prefix/src/libSBML-stamp/libSBML-build] Error 2
make[1]: *** [3rdparty/libSBML/CMakeFiles/libSBML.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/morpheus-lab/homebrew-morpheus/issues

**Comment by jdieg0** [comment]
Hi @yijianglanl,

an update on the macOS side has caused problems with the installation. We have adjusted the Homebrew installation routine so that everything should work again.

Can you please just run this (again):

`brew update`
`brew install morpheus`

Please let me know if there are any other questions or problems.

Best regards,
Diego

**Comment by jdieg0** [comment]
Hi @yijianglanl,

we've just released Morpheus 2.3.6 (announcement coming soon, but the new version is already available via Homebrew), which also addresses the problem with some macOS SDKs not building libSBML, that was also causing your error when installing Morpheus.

A `brew update` and a `brew install morpheus` should now fix the problem on your M2 MacBook Pro.

Please note that the SBML import feature is temporarily disabled due to the mentioned problem, but everything else should work perfectly.

Best regards,
Diego

**Comment by yijianglanl** [comment]
Thank you!

Yi
